### ISSUE TITLE
Windows OS bug

### ISSUE THREAD

**Issue by creold** [joshbduncan/AiCommandPalette#8]
Let me show you another old  Adobe ScriptUI bug on Windows OS. I work on a Mac, but friends told me about it.

In different versions of Adobe Illustrator, when we run scripts that have a dialog, unpredictably we can get the Alt+Tab effect when we click on controls that close the active dialog window (dialog.close()). The File Explorer is shown for a moment. This also happens to your script. The reason for the bug is unknown. This happens if you run the scripts with dialog in any way: drag-n-drop, File > Scripts, third-party scripts extensions. There are small scripts with a dialog window, where this bug is not detected.

Sharing this so you know. But there doesn't seem to be anything we can do about it 😔 PC users will probably not be happy about this effect every time they click.

https://user-images.githubusercontent.com/32217031/185533828-7c075e6b-dd3b-460f-9344-a2092323b89d.mp4

**Comment by joshbduncan** [comment]
Oh, that is bad 😢. So that happens on any script that presents a ScriptUI dialog on Windows?

**Comment by creold** [comment]
Alas, there are ScriptUI dialogs on Windows that don't have this bug. But I couldn't find the exact blocks of code in different scripts that cause this effect. I will try again to take different scripts with and without the bug and start testing the code in detail. I will let you know if I can find the reasons for this effect for ScriptUI dialogs.

An example of my scripts when there was no effect, but in another script it appeared


https://user-images.githubusercontent.com/32217031/185728947-7ff0dc43-af44-4bdb-9c94-3a3eb3f3f0c2.mp4

**Comment by creold** [comment]
After all, my old conjectures are once again confirmed. On the PC, we can't make the ScriptUI dialog element active at once for the user's convenience. This causes the effect of changing windows when the dialog is closed. The only solution is to check `$.os` when setting `active = true` attribute.

`if (/mac/i.test($.os)) element.active = true;`

https://user-images.githubusercontent.com/32217031/185734623-094c2497-da28-4a14-9755-95db3c8536f0.mp4

**Comment by joshbduncan** [comment]
Oh, that's terrible. The whole point of the command palette is you can easily hit a key command and start typing right away without taking your hands off of the keyboard. This bug really messes up that workflow if you have to use your mouse to click into the search field.

I wonder if setting the field to after a key is pressed causes the same bug? Maybe I could catch the first key press, activate the search field and insert the character, then the field would work as normal after that. I have an old PC so I may try downloading Ai on it and trying a few different things.

**Comment by creold** [comment]
I think after `dialog.show()` it might work to capture the first keystroke to activate the field.

**Comment by creold** [comment]
I tried this trick for PC. On mouse event `mouseover` activate a field. Since this event handler is started after the dialog is initialized, there is no Alt+Tab effect after closing the ScriptUi dialog.
```
  if (/mac/i.test($.os)) {
    q.active = true;
  } else {
    win.addEventListener('mouseover', function () {
      q.active = true;
    });
  }
```
The key event to activate the field doesn't work unless there is some active item in the dialog. `win.addEventListener('keydown', function () {}`. So I thought about a mouse event, but that's not an ideal solution either.

https://user-images.githubusercontent.com/32217031/186110723-96aa9562-0146-45e4-872c-43a0febec52c.mp4

**Comment by joshbduncan** [comment]
Hey @creold, I just pushed up PR #9  with a temporary fix for this. I like you idea of using the mouseover event and that may be the best option. You can read all of the details in the PR, but for now, if the user is on a Windows machine the query field is not set to active and the user would have to click in the field to start typing (this affects the workflow builder too).

I also included an option to toggle (disable/enable) this fix in case someone doesn't mind the flickering. I plan to load Illustrator on a PC I have and see if I can come up with a few more options but it doesn't look promising.

Let me know your thoughts. Thanks!

**Comment by creold** [comment]
Hi @joshbduncan. I checked this version with "Disable/Enable Windows Flicker Fix" on PC. It works. But I, as a user, can't tell from this caption what state the option is in now. If you already know `false` or `true` at startup, I suggest dynamically changing the text "Disable Windows Flicker Fix" and "Enable Windows Flicker Fix".

I was talking to designers working on Windows PCs about the `mouseover` event. With this solution, the user is forced to pick up the mouse and hover over the script dialog box before they start typing on the keyboard. One quote: _"It's easier for me to make the input field activation code via AutoHotKey"_. But this is a workaround not available to every average user. Maybe you can find a different solution

**Comment by joshbduncan** [comment]
Yeah, my intention is to have the menu item say either Enable or Disable but it requires me to move a few things around so I just wanted to get your thoughts on this simple temp approach before I made any changes to the menu system. I'll let you know once I've got the required changes made.

As for actually fixing the bug, I haven't had a chance to load Ai on my Windows computer yet but I have a few things I want to try to see if I can keep the functionality the same between Mac and Windows. I'm just not sure any will work since they are somewhat hackey. I'll let you know how it goes.

Thanks again!

**Comment by joshbduncan** [comment]
@creold, so I cleaned things up a bit in the PR and plan to merge it as it is for now. I've already built out the "enable/disable" menu feature too but it involved changing how I build all of the menus so I'm putting that in another branch and will create another PR for that once I've got everything complete. Thanks again for your help!

**Comment by creold** [comment]
@joshbduncan, ok. With small iterations your script gets better and better.

**Comment by joshbduncan** [comment]
@creold, I just pushed PR #10 with the updated menu building system. All of the menu commands are not built until after the user data is loaded now. This allows me to check and see if the winFlickerFix is enabled or disabled, so now the command will either say "Enable" or "Disable" depending on the current setting. This also allows me to not show that option at all if the user is on a mac so if you are on a mac you would need to comment out line 1316 to actually test the functionality.

```javascript
if (menuItems[i].value == "toggleWinFlicker" && /mac/i.test($.os)) continue;
```

I have also moved the config commands to the bottom and now build that part of the data object dynamically by iterating over a simple array of config command objects. I tried this approach for the tool and menu commands since it's a cleaner-looking solution but it slowed down the initial load of the palette so I reverted back.

Finally, there are two new strings that I would need you to translate for me when you have time.

```
There are no workflows to edit.
No tools are currently available.
```

Have a look over everything when you get the time and let me know what you think. Thanks!

**Comment by creold** [comment]
@joshbduncan, it seemed to me that you forgot to activate the input if winFlickerFix is disabled. If the mac OS or the flicker is disabled
```
  if (/mac/i.test($.os) || !data.settings.hideWinFlicker) {
    q.active = true;
  } else if (data.settings.hideWinFlicker) {
    win.addEventListener("mouseover", function () {
      q.active = true;
    });
  }
```
Also for the Russian and German versions you need a translation of winFlickerFix.
`Disable Windows Flicker Fix` - `Отключить исправление проблемы моргания`
`Enable Windows Flicker Fix` - `Исправить проблему моргания`
`There are no workflows to edit.` - `Нет наборов для редактирования`
`No tools are currently available.` - `Инструменты в данный момент недоступны`

P.S. News: it looks like Adobe fixed the flicker problem due to active ScriptUI elements in the new releases 26.4.1, 26.5 on PC. Tested by me and another designer. But the option in the menu is still relevant for older versions and maybe Adobe will again break what it fixed in the next releases.

**Comment by joshbduncan** [comment]
Yep, I had removed the first half of that of statement so I could test the functionality and when I typed it back I forgot the part that checks the user setting. I'll get it updated. Good catch.

And it is great to hear they fixed the bug, but I do agree that keeping the functionality for older users would be best. I guess I can add a version check to this off statement as well so that if they are on Windows but using a new version of Ai then I can just activate field. That's until Adobe breaks it again 🤣.

Thanks so much for your continued help!

**Comment by creold** [comment]
"That's until Adobe breaks it again" — and the list will be updated with even or odd versions. There seems to be a joke among CorelDraw users that odd releases are more stable than even releases. 😁

**Comment by joshbduncan** [comment]
@creold, I've cleaned up the code a bit and also implemented a check for any Ai version where the flicker bug has been fixed. See code snippets below...

I feel the windows version checker is a little clumsy, to be honest. I almost think I should just ditch the version checker part and have the event listener applied to every windows user. Then if they don't like it they can just disable using the config command. It just seems to me, that trying to track all of the versions where Adobe actually fixed the problem would be hard and would potentially require people to redownload the script every time Adobe releases an update to Ai.

What do you think?

Also, on my Mac, I've noticed that even if I disable the q field I can just hit the tab button to active it immediately. Can you confirm this on the PC? I tried loading Ai on the PC I have but it didn't meet the minimum requirements so I haven't been able to test that.

## Updated Code Snippets

Get the current system operating system type for easy access.

```javascript
var sysOS = /mac/i.test($.os) ? "MAC" : "WIN";
```

Check the system os and currently fixed Ai versions to determine whether or not to enable the flicker fix when showing the command palette.

```javascript
var winFlickerFixedVersions = ["26.4.1", "26.5"];
var hideWinFlicker =
  sysOS == "MAC" ||
  (sysOS == "WIN" && winFlickerFixedVersions.includes(aiVersion.toString()))
    ? false
    : data.settings.hideWinFlicker;
```

Either set q to active or add the event listener in the command palette.

```javascript
if (hideWinFlicker) {
  win.addEventListener("mouseover", function () {
    q.active = true;
  });
} else {
  q.active = true;
}
```

Hide the "Enable/Disable Windows Flicker Fix" config command.

```javascript
if (
  (menuItems[i].value == "toggleWinFlicker" && sysOS == "MAC") ||
  (menuItems[i].value == "toggleWinFlicker" &&
    sysOS == "WIN" &&
    winFlickerFixedVersions.includes(aiVersion.toString()))
)
  continue;
```

**Comment by creold** [comment]
@joshbduncan "Tab" button activates the input field? My goodness, Josh, I think we're on the way to a great solution.
Step 1
```javascript
  if (/mac/i.test($.os)) {
    q.active = true;
  } else {
    simulateTab();
  }
```
Step 2
```javascript
function simulateTab() {
  var folder = Folder.myDocuments + '/Adobe Scripts/';
  if (!folder.exists) Folder(folder).create();
  try {
    var f = File(folder + '/' + 'AiCommandPalette.vbs');
    if (!f.exists) {
      var str = 'Set WshShell = WScript.CreateObject("WScript.Shell")\
                  WshShell.SendKeys "{TAB}"';
      f.open('w');
      f.write(str);
      f.close();
    }
    f.execute();
  } catch(e) {}
}
```
And no complicated checks and configuration commands. One small function for the script and a giant leap for mankind. 😀 I already tried this on Windows 7, 10 with Illustrator CS6, CC 2017-2022.

https://user-images.githubusercontent.com/32217031/189745388-8e67e0fa-697b-4b75-aef1-bd505e79dfed.mp4

**Comment by joshbduncan** [comment]
👏 Now that is a creative solution! I can't test it on my end but the screen recording looks great. And it's definitely simpler to integrate. I'll let you know when I have it updated and I will make sure to put your name in the code and on the readme for this contribution. Thanks!

**Comment by creold** [comment]
I'm already thinking about how to use this for my scripts. Sometimes the element that should be active is not the first in the window. It is enough to call the Tab key N times. For example, if the input field is the third element of the dialog box.

I made a customizable function to pass the key code and number of calls as arguments
```js
if (/mac/i.test($.os)) {
  input.active = true;
} else {
  simulateKeyPress('{TAB}', 3);
}

function simulateKeyPress(k, n) {
  if (!n) n = 1;
  try {
    var f = new File(Folder.temp + '/' + 'keyPress.vbs');
    var s = 'Set WshShell = WScript.CreateObject("WScript.Shell")\n';
    while (n--) {
      s += 'WshShell.SendKeys "' + k + '"\n';
    }
    f.open('w');
    f.write(s);
    f.close();
    f.execute();
  } catch(e) {}
}
```

I know a designer who automates Illustrator on Windows via AutoHotKey. His Tab key is binded to the menu, and when the script tries to execute VBS, AutoHotKey catches Tab pressing and the dialog window doesn't get the event. Bad user case  😞

**Comment by joshbduncan** [comment]
@creold, I've got a new branch and PR #11 set up for your fix. I think it's the best solution. I slightly modified the code to make it look similar to the code already in the script but the functionality is the exact same. I can't test on my mac but I can see the VBS file being created and it looks right when I open it up in VS Code.

If you want to clone it and just try it out to make sure all works, I'll get it merged and create a new version of Ai Command Palette that includes all of the recent changes.

As for the designer automating with AutoHotKey, I think it is impossible to account for all of the possible edge cases. They are changing the fundamental way their computer works (I do the same with my caps lock key) so I'm sure they understand doing so can have unforeseen consequences.

Thanks again for all of your help!

**Comment by creold** [comment]
I checked the script from PR #11, `simulateKeyPress()` function works, input field is activated. I looked at the SendKeys table, everywhere the keys are wrapped in curly brackets. So you can put them in a function, and the argument will be the name of the key.
```js
  if (sysOS === "mac") {
    q.active = true;
  } else {
    simulateKeypress("TAB", 1);
  }
....
data += 'WshShell.SendKeys "{' + k + '}"\n';
```
Of course, if we assume that after 26.4.1 the blinking problem is fixed, we can leave your `sysOS == "WIN" && winFlickerFixedVersions.includes(aiVersion.toString())` check. To call VBS on early versions. Only maybe checking `aiVersion > 26.4` is enough here for now, so that you don't put a list of versions into the array. This will partially solve the problem with third-party utilities that remap keys. What do you think?

**Comment by joshbduncan** [comment]
Yeah, I like that...

First, check if the fix should be enabled...

```javascript
var disableWinFlickerFix = sysOS === "win" && aiVersion > 26.4 ? true : false;
```


Then only simulate the key press if the system is Windows with Ai version <= 26.4...

```javascript
  if (sysOS === "mac" || disableWinFlickerFix) {
    q.active = true;
  } else {
    simulateKeypress("TAB", 1);
  }
```

Seems to work for me if I manually set the aiVersion to 23 and the sysOS to "win". Pushing an updated to the PR now. If all looks good to you I'll get this merged into main.

Thanks!

**Comment by creold** [comment]
I described it incorrectly. In 26.4.1 it was also fixed, so the check `aiVersion >= 26.4`. I checked your updated PR on PC.

**Comment by joshbduncan** [comment]
Gotcha! So I actually switched the logic around and I think it reads better. If sysOS === 'win' and aiVersion < 24, enable the fix. PR #11 has been updated.

Check whether or not to enable the fix

```javascript
var windowsFlickerFix = sysOS === "win" && aiVersion < 26.4 ? true : false;
````

If enabled, then do the simulated keypress...

```javascript
if (windowsFlickerFix) {
  simulateKeypress("TAB", 1);
} else {
  q.active = true;
}
```

**Comment by creold** [comment]
Yeah, it looks shorter. Checked it on a PC.

**Comment by joshbduncan** [comment]
Got it merged in. Thanks @creold!
